### ISSUE TITLE
addCountryCode Replacing Zeros with Country Code

### ISSUE THREAD

**Issue by macconnolly** [ahmedbilal/Add-Country-Code-To-Iphone-Contacts#3]
The logic that you are using for addCountryCode in your program.py does not make any sense. Why are you replacing the first character character matching "0" Are you trying to replace the 0th place and append the number after?

Instead, you should just return the country code appended to the number since you've previously determined that the number here does not have a country code at all. 

So what you have on line 40: `return no.replace("0",countryCode,1)` is wrong. 

You should **replace line 40 with**: `return countryCode + no`. 

At least with US phone numbers this is what fixes your script. I just can't wrap my head around why you are replacing at the first instance of a "0". Nowhere else in the script are you adding a 0 at the beginning of the number. 

You could also fix this by adding a 0 to the beginning of numbers that do not have a country code, and then your replace would work fine. In this case you should remove what is on line 40 and replace it with the following:

```
newNumber =  0 + no;
return newNumber.replace("0",countryCode,1)
```
Here's a working version of the file modified with the first fix (just change the file to end in .py instead of .txt
[program-first-fixed.txt](https://github.com/ahmedbilal/Add-Country-Code-To-Iphone-Contacts/files/1415695/program-first-fixed.txt)

**OR**

Here's a working version of the file modified with the second fix (just change the file to end in .py instead of .txt):
[program-fixed.txt](https://github.com/ahmedbilal/Add-Country-Code-To-Iphone-Contacts/files/1415692/program-fixed.txt)

**Comment by ahmedbilal** [comment]
@macconnolly Actually, I created this 3 years ago when my father got iPhone 4s. It was not factory unlocked and don't recognize (show name of person even if it is in **Contacts App**) mobile phone numbers (or any number) without country code. So, our usual number in my city Lahore, Pakistan landline numbers have 04x, xxxxxxx format and mobile number have 03xx, xxxxxxx format. So, when adding country code (in my case +92) there is no need for that leading 0. Thats why i replace that leading 0 by country code and the last argument `newNumber.replace("0",countryCode,**1**)` was to tell the replace function to replace only one instance of "0" with country code so that it won't replace all 0's with countryCode. Hope, you understand that. 

Actually, I was new to python then and haven't had much experience. 😃

**Comment by macconnolly** [comment]
Ah, makes sense now! I forked, updated, and actually my entire university in the states is using this now for students that go abroad - left all the credit to you. So four years later you’re still out here making a difference!

Thanks for the code, it’s really helpful.

**Comment by ahmedbilal** [comment]
@macconnolly Thank you very much. I am thankful for your compliments. Add your name too. Good for both of us 😃 .

**Comment by ahmedbilal** [comment]
@macconnolly which university?
